// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq2LA8L4pxWkq4LzxvBV8vgCx8j2hs8Uo',
    appId: '1:1066071076679:web:8f28e85da220b8d4442662',
    messagingSenderId: '1066071076679',
    projectId: 'send-c0a9a',
    authDomain: 'send-c0a9a.firebaseapp.com',
    storageBucket: 'send-c0a9a.appspot.com',
    measurementId: 'G-CS8J0DREEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASRSMvEraZj2UjMsb3WrrxorgAgf7US-U',
    appId: '1:1066071076679:android:dfccaf6b393ae04a442662',
    messagingSenderId: '1066071076679',
    projectId: 'send-c0a9a',
    storageBucket: 'send-c0a9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbtmzDuNyaeJwH312dPy9krvpti9WWT8U',
    appId: '1:1066071076679:ios:d3ce98edd897a776442662',
    messagingSenderId: '1066071076679',
    projectId: 'send-c0a9a',
    storageBucket: 'send-c0a9a.appspot.com',
    iosClientId: '1066071076679-crojtrm80jlabt6f2c1d0oo1qjs0h4gj.apps.googleusercontent.com',
    iosBundleId: 'com.example.send',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbtmzDuNyaeJwH312dPy9krvpti9WWT8U',
    appId: '1:1066071076679:ios:d3ce98edd897a776442662',
    messagingSenderId: '1066071076679',
    projectId: 'send-c0a9a',
    storageBucket: 'send-c0a9a.appspot.com',
    iosClientId: '1066071076679-crojtrm80jlabt6f2c1d0oo1qjs0h4gj.apps.googleusercontent.com',
    iosBundleId: 'com.example.send',
  );
}
